export const SET_STORY = "SET_STORY";
export const SET_VIEW = "SET_VIEW";
export const SET_ACTIVE_TOP_TAB = "SET_ACTIVE_TOP_TAB";
export const SET_ACTIVE_BOTTOM_TAB = "SET_ACTIVE_BOTTOM_TAB";
export const SET_SCHEME = "SET_SCHEME";

export const INVALIDATE_INIT = "INVALIDATE_INIT";
export const REQUEST_INIT = "REQUEST_INIT";
export const RECEIVE_INIT = "RECEIVE_INIT";

export const SELECT_SEMESTER = "SELECT_SEMESTER";

export const RECEIVE_NOTIFY = "RECEIVE_NOTIFY";

export const RECEIVE_EXIT = "RECEIVE_EXIT";

export const SET_ACTIVE_SCHEDULE = "SET_ACTIVE_SCHEDULE";
export const INVALIDATE_SCHEDULE = "INVALIDATE_SCHEDULE";
export const REQUEST_SCHEDULE = "REQUEST_SCHEDULE";
export const RECEIVE_SCHEDULE = "RECEIVE_SCHEDULE";
